name: Deploy pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        working-directory: slides
        run: npm install
      - name: Build
        working-directory: slides
        run: npm run build -- --base /rust-chat-workshop/
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'
      - name: Trunk build
        working-directory: app
        run: trunk build --release --public-url rust-chat-workshop/app
      - name: Copy
        run: cp -r app/dist slides/dist/app
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: slides/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}