name: Deploy pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        working-directory: slides
        run: npm install
      - name: Build
        working-directory: slides
        run: npm run build -- --base /rust-chat-workshop/
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: slides/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}